### ISSUE TITLE
Additive Noise Reparameterization

### ISSUE THREAD

**Issue by kefirski** [senya-ashukha/variational-dropout-sparsifies-dnn#2]
Hi Arsenii,

I have noticed quite strange thing in your code.

https://github.com/ars-ashuha/variational-dropout-sparsifies-dnn/blob/master/nets/layers.py#L89
`si = T.sqrt(T.dot(input * input, T.exp(log_alpha) * self.W * self.W)+1e-8)`

Instead of multiplying `input^2` with `T.exp(log_sigma2`), you obtain `sigma^2` from `alpha * W^2` and thus additive reparameterization takes no effect in the case of big `alpha`.

The same thing you have in conv layers.

**Comment by senya-ashukha** [comment]
Hi, Daniil! 

It's absolutely the same construction. Besides clipping `T.exp(log_alpha) * self.W * self.W` can be replaced with `T.exp(self.log_sigma2 - T.log(self.W ** 2)) * self.W * self.W` that is exatly `log_sigma_2`.

The beautiful thing about ART is that you have to change the only parametrization while evaluation is the same.

**Comment by kefirski** [comment]
Yep, It's the same thing, but if we will look at this equation without local reparameterization we will see that in current implementation you have `implied_weight = W + W^2 * alpha * eps` and thus variance of gradient will remain the same

**Comment by senya-ashukha** [comment]
Actually no. Let's move to math to see it clearly. We are interested in `d implied_weight / d log_sigma2 `: 

```
implied_weight = W + W^2 * alpha * eps
implied_weight = w + w^2 * exp(log_sigma2) * 1/exp(T.log(self.W ** 2)) * eps 
implied_weight = w + exp(log_sigma2) * eps 
```

After several lines, we can see `d implied_weight / d log_sigma2` does not depend on alpha that's why thought "additive reparameterization takes no effect in the case of big alpha" is wrong.

**Comment by kefirski** [comment]
Yep, you are absolutely right. I forgot that alpha is obtained from `sigma` and `W`.
Thank you for help!

**Comment by senya-ashukha** [comment]
Wellcome!
