### ISSUE TITLE
cudnn version?

### ISSUE THREAD

**Issue by TideDancer** [senya-ashukha/variational-dropout-sparsifies-dnn#3]
Hi I am not able to run the experiments except the lenet300-100. The error I got corresponds to the convolution layer. Also, recently theano changes backend to gpuarray. So I wonder should I use specific version of cuda/cudnn? or any additional config of using gpuarray?

**Comment by TideDancer** [comment]
figured out, cudnn 5

**Comment by senya-ashukha** [comment]
Hi, glad you could solve it.
