### ISSUE TITLE
failed to run on CPU

### ISSUE THREAD

**Issue by agnonchik** [senya-ashukha/variational-dropout-sparsifies-dnn#4]
Hi guys, I have a question. Is GPU mandatory to run lenet-5?

I tried to run it on CPU:
`THEANO_FLAGS='floatX=float32,device=cpu,lib.cnmem=1' ipython experiments/lenet/lenet5-ard.py`
and got the error:

ImportError                               Traceback (most recent call last)
variational-dropout-sparsifies-dnn/experiments/lenet/lenet5-ard.py in <module>()
      5 from nets import objectives
      6 from theano import tensor as T
----> 7 from nets import optpolicy, layers
      8 from lasagne import init, nonlinearities as nl, layers as ll
      9 from lasagne.layers.dnn import Pool2DDNNLayer as MaxPool2DLayer

variational-dropout-sparsifies-dnn/nets/layers.py in <module>()
      5 from lasagne.nonlinearities import rectify
      6 from lasagne.layers.base import Layer
----> 7 from lasagne.layers.dnn import Conv2DDNNLayer as ConvLayer
      8 from theano.sandbox.cuda import dnn
      9 from theano.sandbox.rng_mrg import MRG_RandomStreams as RandomStreams

lib/python2.7/site-packages/lasagne/layers/dnn.py in <module>()
     40 else:
     41     raise ImportError(
---> 42         "requires GPU support -- see http://lasagne.readthedocs.org/en/"
     43         "latest/user/installation.html#gpu-support")  # pragma: no cover
     44 

ImportError: requires GPU support -- see http://lasagne.readthedocs.org/en/latest/user/installation.html#gpu-support

**Comment by senya-ashukha** [comment]
Hi,

Thank you for tracking the bug, unfortunately, our code working only with GPU. But fortunately, it's very easy to fix, if you replace GPU Convolution (dnn.dnn_conv) in Conv2DVarDropOutARD on CPU one it will fix the issue.

**Comment by agnonchik** [comment]
OK, thanks.
