### ISSUE TITLE
How to approximate the D_KL?

### ISSUE THREAD

**Issue by XinDongol** [senya-ashukha/variational-dropout-sparsifies-dnn#5]
Could you please share codes of your method that can be used to approximate D_KL(k_1, k_2 and k_3)?

**Comment by senya-ashukha** [comment]
Hi, it had already been here https://github.com/ars-ashuha/variational-dropout-sparsifies-dnn/blob/master/nets/layers.py#L93

**Comment by XinDongol** [comment]
Thanks a lot. However I mean the code to get k_1, k_2 and k_3? 
You mentioned in your paper that 

>Original −DKL was obtained by averaging over 107 samples of ? with less value of −DKL are presented in Fig. 1. Original −DKL was obtained by averaging over 107 samples of ? with less than 2×10−3 variance of the estimation.

Could you please share codes of this process?
Thanks in advance

**Comment by da-molchanov** [comment]
Added a [notebook](https://github.com/ars-ashuha/variational-dropout-sparsifies-dnn/blob/master/KL%20approximation.ipynb) that does exactly that.

**Comment by XinDongol** [comment]
@ars-ashuha @da-molchanov thanks a lot!
