### ISSUE TITLE
How do you choose the threshold?

### ISSUE THREAD

**Issue by shi27feng** [senya-ashukha/variational-dropout-sparsifies-dnn#9]
Dear author,
I found that you choose 3 as threshold for the mask of weights, I am curious how did you pick up this value?
Thanks a lot!
Feng

**Comment by senya-ashukha** [comment]
Hi, Feng

Thank you for the question!

We used a histogram of log_alpha, that turned out to be a distribution with two modes, modes were clearly separated at log_alpha ~ 3. Of course, the best you can do to plot an accuracy vs alpha on a validation set and choose the best for your problem.

Arsenii

**Comment by shi27feng** [comment]
Thanks for the prompt reply.
